TERMUX_PKG_HOMEPAGE=https://mega.io/
TERMUX_PKG_DESCRIPTION="Provides non UI access to MEGA services"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.0.0"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=git+https://github.com/meganz/MEGAcmd
TERMUX_PKG_GIT_BRANCH=${TERMUX_PKG_VERSION}_Linux
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
# dbus is required for $PREFIX/var/lib/dbus/machine-id
TERMUX_PKG_DEPENDS="c-ares, cryptopp, dbus, ffmpeg, freeimage, libandroid-glob, libc++, libcurl, libicu, libsodium, libsqlite, libuv, mediainfo, openssl, pcre, readline, zlib"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DUSE_FFMPEG=ON
-DUSE_PCRE=ON
-DUSE_LIBUV=ON
-DUSE_PDFIUM=OFF
-DFULL_REQS=OFF
-DVCPKG_ROOT=FALSE
-DENABLE_MEGACMD_TESTS=OFF
"

termux_step_post_get_source() {
	# We use `config.h` generated by configure script instead of this one.
	local f="sdk/include/mega/config-android.h"
	if [ -f "${f}" ]; then
		rm -f "${f}"
		echo '#error DO NOT INCLUDE ME!' > "${f}"
	else
		termux_error_exit "Source file '${f}' not found."
	fi
}

termux_step_pre_configure() {
	# CMake's FindPkgConfig honors pkg-config output. If PKG_CONFIG_SYSROOT_DIR is
	# set in the environment, pkg-config will prefix absolute include paths with it.
	#
	# Termux .pc files already contain full $TERMUX_PREFIX include/library paths,
	# so a sysroot of $TERMUX_PREFIX would yield duplicated paths like:
	#   $TERMUX_PREFIX$TERMUX_PREFIX/include
	# which breaks CMake imported targets (e.g. PkgConfig::cares).
	unset PKG_CONFIG_SYSROOT_DIR

	# Ensure we always use a pkg-config that does not apply a sysroot, even if the
	# outer environment re-exports PKG_CONFIG_SYSROOT_DIR later.
	local wrapper_dir="$TERMUX_PKG_BUILDDIR/_wrapper/bin"
	mkdir -p "$wrapper_dir"
	local real_pkg_config
	real_pkg_config="$(command -v pkg-config)"
	cat > "$wrapper_dir/pkg-config" <<-'EOF'
		#!/bin/sh
		unset PKG_CONFIG_SYSROOT_DIR
		exec "__REAL_PKG_CONFIG__" "$@"
	EOF
	sed -i "s|__REAL_PKG_CONFIG__|$real_pkg_config|" "$wrapper_dir/pkg-config"
	chmod +x "$wrapper_dir/pkg-config"
	export PKG_CONFIG="$wrapper_dir/pkg-config"
	export PATH="$wrapper_dir:$PATH"

	export OBJCXX="$CXX"

	LDFLAGS+=" -landroid-glob -lpcrecpp -lz"
	LDFLAGS+=" $($CC -print-libgcc-file-name)"

	# Fix build against FFmpeg 6.0:
	CPPFLAGS+=" -DCODEC_CAP_TRUNCATED=0"
}
